name: Build/Publish

on:
    push:
        branches:
            - master
            - develop
            - develop-*

jobs:
    main:
        uses: lumeweb/github-node-deploy-workflow/.github/workflows/main.yml@master
        secrets: inherit
